# Generated by Django 4.1.7 on 2023-03-11 10:57

from django.db import migrations
from django.core.management import call_command


def func(apps, schema_editor):
    call_command("loaddata", "cinema_service_db_data.json")


class Migration(migrations.Migration):
    dependencies = [
        ("cinema", "0001_initial"),
    ]

    operations = [migrations.RunPython(func)]
